<?xml version="1.0" encoding="utf-8"?>
<SPSSchema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://spsconsortium.net/schema/SPS.xsd">
  <ProgramName>Directory Compare</ProgramName>
  <Version>3.52</Version>
  <ReleaseDate>2016-03-05</ReleaseDate>
  <Category>Files - Comparison</Category>
  <Description>Directory Compare is a utility to help you keeping copies of your important directories (documents, programs under development and so on) in a backup hard disk or any other storage system (like 100Mb diskettes), as well as in a compressed .zip file (only in version 2.53). The backup may be made automatically (in unattended mode) or by using a friendly user interface. I always have two or more copies of my important documents and I refresh them very often. I prefer to save exact copies of my working directories (rather than using some backup program, because it is faster and makes easier to open the old copy to recover some element or part that was better in the previous version. To make this process easier I wrote many years ago the first version of the program cpy which is included with my Console Utilities. It is a command line program, which makes it very convenient to use from a desktop shortcut that after a single click copies to my backup hard disk all modified elements in my working directories. Users that do not want to remember command lines options may use Cmd Line Shell to have a more user-friendly interface. Directory Compare is a kind or GUI version of cpy: it has far less options but its visual interface makes easier selctive copies. For instance, modern compilers generate an incredible amount of auxiliary data, which speeds up compilation, but takes a lot of storage space. (For instance, the source files of Directory Compare are less than 100 Kb, but the auxiliary files generated by the compiler occupy 7,500 Kb!) Usually you do not want this kind of auxiliary files in your backup disk: they are very large and can be easily recreated by running the compiler. cpy may be instructed to ask you for confirmation before copying each file, but this is a boring and error prone process. My strategy is to have cpy copy everything during program development and when a version is released, I delete from my main and backup disks auxiliary files. To improve this approach I have written Directory Compare: it will show you side by side the source and backup directories so that you can easily select the files to by copied (from the source to the target or in both directories) and even delete from both directories auxiliary files.</Description>
  <License>Copyright
=========

The program, DirCmp.exe, the help file,  DirCmp.chm, and the
documentation file, DirCmp.pdf, are copyrighted:

Copyright © Juan M. Aguirregabiria 1997-2012
All rights reserved

Other brand and product names are trademarks or registered trademarks of
their respective holders.

Directory Compare is FreeWare; there is no charge for using it and it
may be distributed freely so long as the files are kept together and
unaltered. You may neither sell nor profit from distribution of
Directory Compare in any way. Disclaimer

In no event will the Author be liable to users for any damages,
including but not limited to any lost profits, lost savings or other
incidental or consequential damages arising out of the use or the
inability to use this program, even if the Author has been advised of
the possibility of such damages, or for any claim by other party.</License>
  <ProgramPublisherName>Juan M. Aguirregabiria</ProgramPublisherName>
  <ProgramPublisherWebSite>http://tp.lc.ehu.es/jma/win32/dirco.html</ProgramPublisherWebSite>
  <PackerFormat>zip</PackerFormat>
  <MainExeNames>
    <Exe>
      <ExeFullRelativePath>DirCmp.exe</ExeFullRelativePath>
      <ExeName>Directory Compare</ExeName>
    </Exe>
  </MainExeNames>
  <FirstInstallCreateFiles>dircmp.ini</FirstInstallCreateFiles>
  <CleanUpdate>false</CleanUpdate>
  <BuiltInUpdater>false</BuiltInUpdater>
  <DownloadUrl>http://tp.lc.ehu.es/anonym/win95/drcmp352.zip</DownloadUrl>
  <DownloadSizeKb>6244</DownloadSizeKb>
  <ProgramIconBase64>iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOvQAADr0BR/uQrQAAAg5JREFUOE9jIAasyNESW1lgoP1ompPrr/PT5v+6NGPer0tT5/3YlVMNVYIf/LrUtfPfz3Xn/v1efeb/v/n7//+buf//38n7f+wKKIQqwQ0OVOup/H3bcfH/1+L9/z/n7///MXv//3dp+/89iz98pUNDB6oMN3i+NLj03223Q/9u2B78d9Xi4L9LRgf/ndc9+Hun5kaoEuzAJNjQKGty2oTKGVE78soNJ1dFSprNiBfXnwnGYiAsBVWKCfzyvSI231//c+XDxX+n3Or9l3gi7K9Hl+Mudn52dqgS3EBcU5Rr8cX5b46+PPjvz58/YPz265t/oUe8/mp6q2VAleEGyraKZqsfLf079U7fvxV3l/z7/uv7v19/fv2LOOH316bMfDlUGW4gqims2XK5+u+iu3P+ffrx6V/v5Q6wAWmX4/9a55rNgirDDdh4WJm8pjgdm3tr2t/GS1V/4y+E/5vxaNrf4hv5v0TVRBygyhDgx96yjt835u//sb9ywuYyI+kZabrSuTE61mGzXC7HHA/8m3Q+8k/m0dQPGm5qWYzMjIxQbQjw+3Lz/v8/2/7/+9bz/+/bLjg+PNO1V0iez1hcQ8yFmYNZDKocE/w+mbP//22H/+j45xajbqgS/OD3gaj9//dx/EfHP5dLEmnAvvD9/3cx/kfHP5eIEmfAj9VOTb9WCG5Hx9/nysRCleABDAwAoG42wQ4/NP8AAAAASUVORK5CYII=</ProgramIconBase64>
  <SPSPublisherName>SyMenu Suite</SPSPublisherName>
  <SPSLicense>CC Attribution-NoDerivatives 4.0 International</SPSLicense>
  <SPSProgramReport>http://www.ugmfree.it/ContactMail.aspx</SPSProgramReport>
  <VirusTotalResult>
    <Permalink>https://www.virustotal.com/file/4209a3afbb6ea0bc853aa611259daf462ae66ae067362f7074f2a138e74faaee/analysis/1556190351/</Permalink>
    <DetectionRatio>0/63</DetectionRatio>
  </VirusTotalResult>
</SPSSchema>