<?xml version="1.0" encoding="utf-8"?>
<SPSSchema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://spsconsortium.net/schema/SPS.xsd">
  <ProgramName>FTK Imager Lite</ProgramName>
  <Version>3.1.1</Version>
  <ReleaseDate>2010-10-16</ReleaseDate>
  <Category>Security - Forensic Tools</Category>
  <Description>FTK® Imager is a data preview and imaging tool used to acquire data (evidence) in a forensically sound manner by creating copies of data without making changes to the original evidence. 
FTK Imager will:
- Create forensic images of local hard drives, CDs and DVDs, thumb drives or other USB devices, entire folders, or individual files from various places within the media.
- Preview files and folders on local hard drives, network drives, CDs and DVDs, thumb drives or other USB devices.
- Preview the contents of forensic images stored on the local machine or on a network drive.
- Mount an image for a read-only view that leverages Windows® Internet Explorer® to see the content of the image exactly as the user saw it on the original drive.
- Export files and folders from forensic images.
- See and recover files that have been deleted from the Recycle Bin, but have not yet been overwritten on the drive.
- Create hashes of files to check the integrity of the data by using either of the two hash functions available in FTK Imager: Message Digest 5 (MD5) and Secure Hash Algorithm (SHA-1).
- Generate hash reports for regular files and disk images (including files inside disk images) that you can later use as a benchmark to prove the integrity of your case evidence. When a full drive is imaged, a hash generated by FTK Imager can be used to verify that the image hash and the drive hash match after the image is created, and that the image has remained unchanged since acquisition.
</Description>
  <License>Legal Information
©2012 AccessData Group, LLC All rights reserved. No part of this publication may be reproduced, photocopied,
stored on a retrieval system, or transmitted without the express written consent of the publisher.
AccessData Group, LLC makes no representations or warranties with respect to the contents or use of this
documentation, and specifically disclaims any express or implied warranties of merchantability or fitness for any
particular purpose. Further, AccessData Group, LLC reserves the right to revise this publication and to make
changes to its content, at any time, without obligation to notify any person or entity of such revisions or changes.
Further, AccessData Group, LLC makes no representations or warranties with respect to any software, and
specifically disclaims any express or implied warranties of merchantability or fitness for any particular purpose.
Further, AccessData Group, LLC reserves the right to make changes to any and all parts of AccessData
software, at any time, without any obligation to notify any person or entity of such changes.
You may not export or re-export this product in violation of any applicable laws or regulations including, without
limitation, U.S. export regulations or the laws of the country in which you reside.
AccessData Group, LLC.
384 South 400 West
Suite 200
Lindon, Utah 84042
U.S.A.
www.accessdata.com</License>
  <ProgramPublisherName>AccessData</ProgramPublisherName>
  <ProgramPublisherWebSite>https://www.accessdata.com</ProgramPublisherWebSite>
  <PackerFormat>zip</PackerFormat>
  <MainExeNames>
    <Exe>
      <ExeFullRelativePath>FTK Imager.exe</ExeFullRelativePath>
      <ExeName>FTK Imager Lite</ExeName>
    </Exe>
  </MainExeNames>
  <CleanUpdate>false</CleanUpdate>
  <BuiltInUpdater>false</BuiltInUpdater>
  <DownloadUrl>https://ad-zip.s3.amazonaws.com/Imager_Lite_3.1.1.zip</DownloadUrl>
  <DownloadSizeKb>24739</DownloadSizeKb>
  <ProgramIconBase64>iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOwgAADsIBFShKgAAAAqRJREFUOE99Us9PE2EQ/RKNBw/GhEQ9+IcoMZzQExjiBVSwoB6qcikS/HGQg0CUVjBAISS0GLQC/bEtSkQMCQqGtqiQqAjttoWWtpYuiy1tCUrp89uvKyJEDi8zs/vm7ZuZJcsrIgnbmxByNEGYfoz+tmuorChEtbII2vtlCE+qEZnUIORsRNCupjwNws5mhGgedjwA8U50YdVtRtr/AiqVCrxDjw3BjjW3CZuhIdTdLse5gjz8Cgwi7uYYN86baeQQmdKC+JxdWF+w4WJxCfiJTmysLiIx18+ICd6KNZ5DU70SBfknkfJaWXOcNyLuMuH7R1ng89sWGLrUwLqAmKuXNhvlL1EibUgHB3Hs6HHMjmkRc0viWSfMwYKzG7VVFfj2rh0/o1/Yi+2QBJIeMxTnC3FPdYnmnOzCjOgnJqDD5dKzWJmxIOEb2CXA3HgsqL5xAXdrrmPNZ/tXYN7RjfaGSgSne6jAy10CkuV1LweFohh6bd22PcgCPqceqXkbHtVe3VrediRdUjRi+M0oJmwP6WItOx3oWVF/5wrSgQGWJ13SkqRFckDkFcrLSrAU9kKcfY5VfgAxxqECH9qyI0gNKa8FPa010GmqEJ+zIuE14XVfA0rLKqDv1OFZXy88Q41ZR/S8Kx7j3xGyNiVw2PDb0NGghFJRhA71TfDjWrZE3YmDsJ45gsXRZvoPWJByW+gZW+kV7HpGSPAmJiKNINmXziXN+2eU8Pt2GHIPwJafg+BYC3selhwEpkxI+Uf2RNI/jHhgGEvOHjzN3Qfr6RxEnU8gzhhAotEoAbAHNgky2TyTSRPR85UYTlGR/MNIRAKECEtUQCawuBOsMSPnVIzWy+4pYsjdj968QyDuORcRRZFCkOP/IJCY8GOrnh0fIdZbpfgNFeMfpNmWGg4AAAAASUVORK5CYII=</ProgramIconBase64>
  <SPSPublisherName>Rebus</SPSPublisherName>
  <SPSLicense>CC Attribution-ShareAlike 4.0 International</SPSLicense>
  <SPSProgramReport>mailto:rebus@tipiloschi.net</SPSProgramReport>
</SPSSchema>