<?xml version="1.0" encoding="utf-8"?>
<SPSSchema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://spsconsortium.net/schema/SPS.xsd">
  <ProgramName>glogg</ProgramName>
  <Version>1.1.4</Version>
  <ReleaseDate>2017-04-22</ReleaseDate>
  <Category>Text - Viewers</Category>
  <Description>glogg enables you to use regular expressions to search for interesting events in your log files. It presents a results window which, together with complex regular expressions allows easy isolation of the meaningful lines amongst the noise.

glogg has been primarily developed to help spot and understand problems in huge logs generated by embedded systems. It can be equally useful to a sysadmin digging through logs from databases or web servers.

The main design goals for glogg are:
- it should be fast
- it does not have any limit on the size of files it can handle
- it provides a clear view of the matches even in heavily cluttered files.
</Description>
  <License>GPLv3</License>
  <ProgramPublisherName>Nicolas Bonnefon</ProgramPublisherName>
  <ProgramPublisherWebSite>http://glogg.bonnefon.org</ProgramPublisherWebSite>
  <PackerFormat>zip</PackerFormat>
  <MainExeNames>
    <Exe>
      <ExeFullRelativePath>glogg.exe</ExeFullRelativePath>
      <ExeName>glogg</ExeName>
    </Exe>
  </MainExeNames>
  <CleanUpdate>false</CleanUpdate>
  <BuiltInUpdater>false</BuiltInUpdater>
  <DownloadUrl>http://glogg.bonnefon.org/files/glogg-latest-x86_64-setup.exe</DownloadUrl>
  <DownloadSizeKb>6620</DownloadSizeKb>
  <ProgramIconBase64>iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAHdSURBVDhPjZBfRINRGMY/6jJiyrJU+5PRRZouUi1GlmXTxUjlu1hGFynRdJHqpqsUE9HFrJsom2iWLLIssruULlZ3k2TjI6M1bT6+7ens7Gy19qd+POec95z3eRwvx+j+Q3Ki2tzf36EeuVzug7Q1FbqrEA6HWWt9WHslvwOSyXesra9WaGh44KooZi3wMyAafYZ1ysqq2sj7upTM/h2QSCTgdh/AZB6jtU7XD42mG0qlqiS/30/fqgYIggCncxc+nx8u3y042Sb0Sz76BkU70JZXGy2rBqRSKSwsLILT7iBN6jcJuH0F2u1n9P38PEB+UDhXDSiydfqEd7KniKJkmTt8xprrGpIkkpssstls7YBYLI7jcIwaI1IGN8kE+EAInGoby/sOEiJBFMX6Pxha9uBBAEb5VbT0TUCmn4d9OwiFogMyWSvtKQsIhUKf+cv8EG02O7jWTewF41AZZqEa4dFiWKEmrbYHvb06ei4LIGiI+SWdTsNkMiOTyaBz6gjNkydkoE5q8HpP6C6SOcSEONRqdTPzltAbjSY4HCtobGx4s1on4fF4wfM2OrQiLpcb5glLjnlKzIyPW6iZnDcGBvsfWX8ZF8EADEZDhZmLRJ5weRnMm6cLN/+F474AXWYhKKE4BgAAAAAASUVORK5CYII=</ProgramIconBase64>
  <SPSPublisherName>Rebus</SPSPublisherName>
  <SPSLicense>CC Attribution-ShareAlike 4.0 International</SPSLicense>
  <SPSProgramReport>mailto:rebus@tipiloschi.net</SPSProgramReport>
</SPSSchema>