<?xml version="1.0" encoding="utf-8"?>
<SPSSchema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://spsconsortium.net/schema/SPS.xsd">
  <ProgramName>yEd Graph Editor</ProgramName>
  <Version>3.23.1</Version>
  <ReleaseDate>2023-03-27</ReleaseDate>
  <Category>Graphics - Diagramming</Category>
  <Description>yEd is a powerful desktop application that can be used to quickly and effectively generate high-quality diagrams.
Create diagrams manually, or import your external data for analysis. Our automatic layout algorithms arrange even large data sets with just the press of a button.</Description>
  <License>yEd Software License Agreement
Version 1.1

This is a legal agreement ("this Agreement") between yWorks GmbH ("yWorks") and the licensee ("the Licensee"). yWorks licenses the yEd Software ("the Software") only if all the following terms are accepted by the Licensee. The Software includes the yEd byte code executable and any files and documents associated with it.

By installing the Software, the Licensee is indicating that he/she has read and understands this Agreement and agrees to be bound by its terms and conditions. If this Agreement is unacceptable to the Licensee, the Licensee must destroy any copies of the Software in the Licensee's possession immediately.
1. LICENSE CONDITIONS
The Licensee is granted a non-exclusive and non-transferable right to install one copy of the Software and use it as an application. The Software may not be used as part of an automated process. The Licensee may not reverse engineer, disassemble, decompile, or unjar the Software, or otherwise attempt to derive the source code of the Software.

The Licensee acknowledges that Software furnished hereunder is under test and may be defective. No claims whatsoever can be made on yWorks based on any expectation about the Software.
2. TERM, TERMINATION AND SURVIVAL
The Licensee may terminate this Agreement at any time by destroying all copies of the Software in possession.

If the Licensee fails to comply with any term of this Agreement, this Agreement is terminated and the Licensee has no further right to use the Software.

On termination, the Licensee shall have no claim on or arising from the Software. The Software and any copies shall be destroyed.
3. NO WARRANTY
The Software is licensed to the Licensee on an "AS IS" basis. The Licensee is solely responsible for determining the suitability of the Software and accepts full responsibility and risks associated with the use of the Software.
4. MAINTENANCE AND SUPPORT
yWorks is not required to provide maintenance or support to the Licensee.
5. LIMITATION OF LIABILITY
In no event will yWorks be liable for any damages, including but not limited to any loss of revenue, profit, or data, however caused, directly or indirectly, by the Software or by this Agreement.
6. DISTRIBUTION
No distribution is to be made of the Software by the Licensee. The Licensee may make one copy of the Software for backup purpose only.
7. AVAILABILITY
The Software is not available to those not permitted by law to have access to the Software.
8. INSERTION OF MARKER
The Software may insert some markers into any output files to identify that the files are generated by the Software. yWorks bears no responsibility for any damages arising.
9. MISCELLANEOUS
This agreement is made and shall be construed in accordance with the laws of Germany.
THIRD-PARTY SOFTWARE AND LICENSES
This Software makes use of the Batik SVG Toolkit, Apache XMLBeans, and Apache POI. The Apache Software License (http://xml.apache.org/batik) applies to them.

This Software makes use of the JIDE Docking Framework and JIDE Action Framework licensed from JIDE Software (http://www.jidesoft.com).

This Software uses icons licensed from Incors GmbH (http://www.incors.com).

This Software includes a Swing LnF created by JGoodies and the dom4j library. The BSD License (http://www.opensource.org/licenses/bsd-license.html) applies to them.

This Software makes use of the FreeHEP VectorGraphics library (http://java.freehep.org). The GNU LESSER GENERAL PUBLIC LICENSE, Version 2.1 (http://java.freehep.org/vectorgraphics/license.html) applies to it.

This Software makes use of the JavaHelp System (https://javahelp.dev.java.net/). The GNU General Public License - Version 2 (https://javahelp.dev.java.net/license.txt) with the class path exception applies to it.

This Software makes use of the svg-viewer rendering engine (http://code.google.com/p/svg-viewer/). The MIT License (http://www.opensource.org/licenses/mit-license.php) applies to it.

The installer for this Software may contain a Java Runtime Environment (JRE) (http://java.com). The SUN MICROSYSTEMS, INC. BINARY CODE LICENSE AGREEMENT with SUPPLEMENTAL LICENSE TERMS (http://java.com/en/download/license.jsp) applies to it. </License>
  <ProgramPublisherName>yWorks</ProgramPublisherName>
  <ProgramPublisherWebSite>http://www.yworks.com/en/products/yfiles/yed</ProgramPublisherWebSite>
  <PackerFormat>zip</PackerFormat>
  <MainExeNames>
    <Exe>
      <ExeFullRelativePath>yed.jar</ExeFullRelativePath>
      <ExeName>yEd Graph Editor</ExeName>
    </Exe>
  </MainExeNames>
  <CleanUpdate>false</CleanUpdate>
  <Dependency>JRE 6 or higher</Dependency>
  <BuiltInUpdater>false</BuiltInUpdater>
  <DownloadUrl>https://www.yworks.com/resources/yed/demo/yEd-3.23.1.zip</DownloadUrl>
  <DownloadSizeKb>35618</DownloadSizeKb>
  <ProgramIconBase64>iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOvAAADrwBlbxySQAAAplJREFUOE99k3tIU2EYh9Vl0E1IjIJpEEVagQaGjaIZ9YfoUDA37ebUHMMuNixIDETBzGoXW5aaYOSFSosU7SLMy+zMo5tzXtvwWt5SwQtaWQnx6zvbqYOkPvDAe77z/r7v/Q4cpzVwJmqI80QBs8CSTsxxlGsTTywl/iLmMwssr4lPHOXqMKf/Db0hfnCUdnqIsY5yFQQiGU9yRR15Nc8i3+kToHd24fWGpOtdyKsNxB/EbUzfijysHAjMqRiwal71Ia34I46EJmCz+w5Is1us3sfPp5IWZqKVKdGNhL9sHF+qMEzgWf0ocqsGERSlgJsHH/FaE3YfDoOX38lktn05xbphfhU9sdBsnYOlfx6NnTMo149DdEYBD/4eyNSN2Orpg4i71IIwtY7Pxjie148qGzqm0Tv6DZ8nF9E1tIB3xikEi+Xw8j4EoeQajklvQXyvCWJlk5KNcZDxbQ3t07AOf0X/2He0D8zjvWkKwiAJfPxPYJdvIOK0RkQpaYRmUVY2xlHwduhndfMkDD2zMNrmQHXNgHne5yfAOtf1OJ1SggsPTJCQDUS3qUU2xkG++lxp7Yh9bKp7BobuWVTTY9i4aQt8haegKLDYNziraUGEkp5lYxx3ymx1edWDqDB8QROZgjFDUwQ39+248ZjGxVwzorNbEKmiEZJJ1bIxjvTSHmlWmQ2FNZ9Q0zoFnXkSe/cfhCytCNcLOyB/1Go/XZRJQayio9kYR1KBhZd4v7Yt84UV2so+hJ1TQBRzE8lPO3E5vw0x5AOKyf0lKpoSpOh4bGwZ/sTfAcGx8BOGQxAqRxI5+RIJxzJ3J+OTuxsj1bSHo/1/PInMj9J64GhYRkKeuS0ux7Qk1RqXSNgcoaITJWra1d75DyenP/j3arNwyPXxAAAAAElFTkSuQmCC</ProgramIconBase64>
  <SPSPublisherName>SyMenu Suite</SPSPublisherName>
  <SPSLicense>CC Attribution-NoDerivatives 4.0 International</SPSLicense>
  <SPSProgramReport>http://www.ugmfree.it/ContactMail.aspx</SPSProgramReport>
  <VirusTotalResult>
    <Permalink>https://www.virustotal.com/gui/file/d9a036962db9e958ad589a11d67f35e28236eabc0793b3f265559690187e34bd/detection/f-d9a036962db9e958ad589a11d67f35e28236eabc0793b3f265559690187e34bd-1679977718</Permalink>
    <DetectionRatio>0/53</DetectionRatio>
  </VirusTotalResult>
</SPSSchema>